### ISSUE TITLE
Installation help on Ubuntu Studio

### ISSUE THREAD

**Issue by drlight-code** [drlight-code/osccontrol-light#44]
Hi @desterritorializ-ada, glad you're interested in my plugin :) let's see if we can make it work for you. 

In order to install and use the plugin you will have to walk through the process of building it first. This is necessary for two reasons. In general, on a Linux system it's tricky to provide pre-compiled binary plugins because there are so many different distributions out there. 

More importantly, in the case of this plugin you will need a pre-compiled version that is specific to each preset definition file that you want to use. The file contains the definition of the controls that you want each instance of the plugin to have and which OSC messages they are mapped to. That's because in order to create controls that can be automated within the host environment, the controls need to be known at construction time of the plugin, so no user interaction is possible in-between. At least I could not find a way to do this using the VST SDK or the JUCE audio plugin abstraction.

Did you try to follow the [compilation instructions](https://github.com/drlight-code/osccontrol-light#compilation)? How far did you proceed? Where did you get stuck and what is the problem that you ran into?

**Comment by desterritorializ-ada** [comment]
Hi! Thank you for the quick response. The truth is that I did not understand what compiling was. I am new to the world of programming. Now I understand that compiling is translating the code written in C++ into a computer language. Some kind of translation for the instructions to be executed? There I started to install CMake and JUCE and got this error (in the console):

`desterritorializada@desterritorializ:~$ mkdir JUCE/build
desterritorializada@desterritorializ:~$ cd JUCE/build
desterritorializada@desterritorializ:~/JUCE/build$ cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:26 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/desterritorializada/JUCE/build/CMakeFiles/CMakeOutput.log".
See also "/home/desterritorializada/JUCE/build/CMakeFiles/CMakeError.log".
desterritorializada@desterritorializ:~/JUCE/build$ 

`

**Comment by drlight-code** [comment]
A CPU processes low-level machine-readable instructions for things like adding, comparing or reading/writing into memory. A compiler translates the high-level language a programmer writes (like C++) into these "codes" that the machine understands.

The first thing to do is to install a c++ compiler, CMake tells you in the error message that it can not find any. I think you should be able to do so by installing the `build-essential` package with your distribution's package manager. On the command-line `apt-get install build-essential` should work.

**Comment by desterritorializ-ada** [comment]
Oh thans for explication!!

I already installed build-essential with command-line. 
I uninstalled Juce and cloned the code again and installed it. I continued with the previous procedure and the error continues, but now more lines appear!!!

The error: 

esterritorializada@desterritorializ:~$ mkdir JUCE/build
desterritorializada@desterritorializ:~$ cd JUCE/build
desterritorializada@desterritorializ:~/JUCE/build$ cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'alsa'
--   No package 'alsa' found
-- Checking for module 'freetype2'
--   No package 'freetype2' found
-- Checking for module 'libcurl'
--   No package 'libcurl' found
-- Checking for modules 'webkit2gtk-4.0;gtk+-x11-3.0'
--   No package 'webkit2gtk-4.0' found
--   No package 'gtk+-x11-3.0' found
-- Configuring juceaide
-- Building juceaide
CMake Error at extras/Build/juceaide/CMakeLists.txt:101 (message):
  Failed to build juceaide

  Scanning dependencies of target juceaide

  [ 12%] Building CXX object
  extras/Build/juceaide/CMakeFiles/juceaide.dir/Main.cpp.o

  [ 25%] Building CXX object
  extras/Build/juceaide/CMakeFiles/juceaide.dir/__/juce_build_tools/juce_build_tools.cpp.o


  [ 37%] Building CXX object
  extras/Build/juceaide/CMakeFiles/juceaide.dir/__/__/__/modules/juce_gui_basics/juce_gui_basics.cpp.o


  In file included from
  /home/desterritorializada/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp:46:


  
  /home/desterritorializada/JUCE/modules/juce_gui_basics/juce_gui_basics.h:322:12:
  fatal error: X11/Xlib.h: No existe el archivo o el directorio

    322 |   #include <X11/Xlib.h>
        |            ^~~~~~~~~~~~

  compilation terminated.

  make[2]: *** [extras/Build/juceaide/CMakeFiles/juceaide.dir/build.make:89:
  extras/Build/juceaide/CMakeFiles/juceaide.dir/__/__/__/modules/juce_gui_basics/juce_gui_basics.cpp.o]
  Error 1

  make[1]: *** [CMakeFiles/Makefile2:133:
  extras/Build/juceaide/CMakeFiles/juceaide.dir/all] Error 2

  make: *** [Makefile:130: all] Error 2



-- Configuring incomplete, errors occurred!
See also "/home/desterritorializada/JUCE/build/CMakeFiles/CMakeOutput.log".
desterritorializada@desterritorializ:~/JUCE/build$

**Comment by drlight-code** [comment]
I missed the notification for this issue somehow.. You are missing the X11 headers (or "include files"). Header files contain the declarations of all the available functions of a library that you can use. X11 is part of the graphical environment on Linux-based systems. I'm not sure which package exactly contains that file on your distribution, here's how you can check in such a case.
- install the `apt-file` utility and call `apt-file update`
- call `apt-file search X11/Xlib.h`
- see that the package `libx11-dev` contains the file `/usr/include/X11/Xlib.h` that you are searching for
- install the `libx11-dev` package
- profit
Keep in mind that this is JUCE that you are compiling which is a dependency of my plugin. You can refer to their build/installation instructions as well in case of trouble, but I will be glad to assist you here as well. I did a quick search and it seems there is not much of an installation guide on Linux. This thread in the forum is helpful though https://forum.juce.com/t/setting-up-on-linux-some-basic-questions-that-googling-didnt-answer/30503/2
You might want to go ahead and install all the dependencies in that post and then continue like above.

**Comment by desterritorializ-ada** [comment]
Hello!

First of all apologies for not answering earlier, I had a very busy few weeks of work and university and added to the fact that I had to reinstall Ubuntu I lost the debugging thread of my installation problems

So I tried again to follow the build instructions and I made pretty good progress. I managed to install 1 by one the libraries that I was missing... so I got to:


cmake ..
-- Checking for module 'libcurl'
--   Found libcurl, version 7.74.0
-- Configuring juceaide
-- Building juceaide
-- Exporting juceaide
-- Configuring done
-- Generating done
-- Build files have been written to: /home/isis/JUCE/build


then, a new obstacle arose when putting the command:

cmake --install . --prefix <juce_install_root>

throws me the error:

bash: syntax error near unexpected `newline' element

I tried several ways and I get that bash error or it redirects me to these instructions:

Usage: cmake --install <dir> [options]
Options:
  <dir> = Project binary directory to install.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --component <comp> = Component-based install. Only install <comp>.
  --prefix <prefix> = The installation prefix CMAKE_INSTALL_PREFIX.
  --strip = Performing install/strip.
  -v --verbose = Enable verbose output.


what can be happening?

sure it's a syntax error, but I transcribed it in several ways and it didn't work

Thank you so much!

**Comment by drlight-code** [comment]
Hi, I guess you will have to replace `<juce_install_root>` with the (so-called "root") folder into which you want to install the JUCE library. That could be something like `/usr/local` for a system-wide installation, or something like `$HOME/local/juce` which I personally prefer because it allows you to keep things more clean and separated. `$HOME` is the value of the `HOME` environment variable that contains the path of your user's home directory, so e.g. `/home/isis`

**Comment by desterritorializ-ada** [comment]
Oh thanks! I feel like I'm advancing at an ant's pace...

managed to install the JUCE library in the isis/home prefix

then I went to the osccontrol-light-main folder (in the terminal) and tried to run ./build_plugins.sh simple-synth track-1 (to see if the GUI version plugin was built, then I'll see how to make it recognize it as vst in Reaper)

gave me this error:

isis@isis-solar:~/Descargas/osccontrol-light-main/build$ cmake -DPRESET_NAMES="simple-synth;track-1" ..
CMake Error at CMakeLists.txt:5 (find_package):
  Could not find a package configuration file provided by "JUCE" with any of
  the following names:

    JUCEConfig.cmake
    juce-config.cmake

  Add the installation prefix of "JUCE" to CMAKE_PREFIX_PATH or set
  "JUCE_DIR" to a directory containing one of the above files.  If "JUCE"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/isis/Descargas/osccontrol-light-main/build/CMakeFiles/CMakeOutput.log".

___________________-


 imagine that it is related to the prefix that I just generated in the installation of the library, but I did not find the file to edit it!!! Or maybe it's an installation problem...

apologies for these problems, I'm very new to linux and English is quite difficult for me.

Thank you!

**Comment by drlight-code** [comment]
Hi Ada,

No worries, I think you are getting there. I'm aware of the fact that this process is quite tedious for non-developers, however as of now there is unfortunately no good alternative to compiling the plugins yourself. I will incorporate the help that you needed into a more detailed installation/compilation guide so that the process will be made hopefully a bit easier for others in the future.

The problem you are seeing now is that, because JUCE was installed in a non-standard location (in your home directory as opposed to globally on the system) you have to tell CMake where to find that copy of the JUCE installation. If `<juce_root>` is the prefix into which you installed JUCE, you can set it for example via the environment variable `CMAKE_PREFIX_PATH`.
Before trying to build the plugin you should run the following command:
```
$ export CMAKE_PREFIX_PATH=<juce_root>
```
Hope this helps!

**Comment by drlight-code** [comment]
Please note, that the environment variable setting is specific to your current shell session. So the command has to be run before building the plugin and in the same terminal window.

**Comment by desterritorializ-ada** [comment]
oh, thank you then for your work and your time!!!

I think I managed to compile it there!


isis@isis-solar:~/Downloads/osccontrol-light-main$ ./build_plugins.sh simple-synth track-1
creating cmake config in 'build' directory
cmake -DPRESET_NAMES=;simple-synth;track-1 ..
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Check for module 'libcurl'
-- Found libcurl, version 7.74.0
-- Checking for modules 'webkit2gtk-4.0;gtk+-x11-3.0'
-- Found webkit2gtk-4.0, version 2.36.0
-- Found gtk+-x11-3.0, version 3.24.30
-- Checking for module 'alsa'
-- Found alsa, version 1.2.4
-- Check for module 'freetype2'
-- Found freetype2, version 23.4.17
creating build target for osccontrol-light-gui standalone application
creating build target for osccontrol-light-gui VST3 plugin
creating build target for simple-synth preset VST3 plugin
creating build target for track-1 preset VST3 plugin
--Configuring done
-- Generating done
-- Build files have been written to: /home/isis/Downloads/osccontrol-light-main/build
building osccontrol plugins...

Now how do I run the GUI application?

Then I'll ask you how to build my own plugins and display them from Reaper, but let's go step by step...

Thanks!!!

**Comment by drlight-code** [comment]
That's great! The binary of the GUI application can be found in the build directory, specifically `build/osccontrol-light_artefacts/Standalone/osccontrol-light`. For convenience I just changed the `build_plugins.sh` script so that it will copy the executable from there to the top-level source directory. I also added some output so that the script tells you about this. You will have to update your current version of the plugin by `git pull`, then build the plugin again. Then you can run the GUI application by just `./osccontrol-light`.

**Comment by drlight-code** [comment]
Marking this as done.
