### ISSUE TITLE
LV2 build target?

### ISSUE THREAD

**Issue by mxmilkiib** [drlight-code/osccontrol-light#45]
Hi! Just wondering if at some point an LV2 builld target can also be set and released? Thanks!

**Comment by drlight-code** [comment]
Hey @mxmilkiib :wave: I uploaded a [pre-release](https://github.com/drlight-code/osccontrol-light/releases/tag/release%2F2023.11-pre) of the current main branch as LV2 and VST3 just now. Please give it a shot, I'll be happy about any feedback.
